import Landing from "../components/Landing";
import Perfection from "../components/Perfection";


export default function Home() {
 

  return (
    <>
      <head>
        <title>Tetraz Trimmers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main>
        <Landing />
        <Perfection />
      </main>

    </>
  )
}
